name: AWS Terraform CI/CD

on:
  push:
    branches:
      - '**'  # Allow from any branch (esp. for Dev)
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - uat
          - production
      destroy:
        description: 'Destroy infrastructure?'
        required: false
        default: 'false'
        type: choice
        options:
          - false
          - true

jobs:
  deploy:
    name: 🌍 Terraform ${{ github.event.inputs.destroy == 'true' && 'Destroy' || 'Deploy' }} ➤ ${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.event.inputs.environment == 'dev' && 'Dev' || github.event.inputs.environment == 'uat' && 'UAT' || 'Prod' }}
    environment: ${{ github.event.inputs.environment }}
    steps:
      - name: 📦 Checkout Repo
        uses: actions/checkout@v4

      - name: ⚙️ Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: 🔐 Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-west-2
          aws-access-key-id: ${{ github.event.inputs.environment == 'dev' && secrets.AWS_ACCESS_KEY_ID_DEV || github.event.inputs.environment == 'uat' && secrets.AWS_ACCESS_KEY_ID_UAT || secrets.AWS_ACCESS_KEY_ID_PROD }}
          aws-secret-access-key: ${{ github.event.inputs.environment == 'dev' && secrets.AWS_SECRET_ACCESS_KEY_DEV || github.event.inputs.environment == 'uat' && secrets.AWS_SECRET_ACCESS_KEY_UAT || secrets.AWS_SECRET_ACCESS_KEY_PROD }}

      - name: 🛠 Terraform Init
        env:
          AWS_ACCESS_KEY_ID: ${{ github.event.inputs.environment == 'dev' && secrets.AWS_ACCESS_KEY_ID_DEV || github.event.inputs.environment == 'uat' && secrets.AWS_ACCESS_KEY_ID_UAT || secrets.AWS_ACCESS_KEY_ID_PROD }}
          AWS_SECRET_ACCESS_KEY: ${{ github.event.inputs.environment == 'dev' && secrets.AWS_SECRET_ACCESS_KEY_DEV || github.event.inputs.environment == 'uat' && secrets.AWS_SECRET_ACCESS_KEY_UAT || secrets.AWS_SECRET_ACCESS_KEY_PROD }}
        run: terraform init

      - name: 📊 Terraform Plan
        if: github.event.inputs.destroy != 'true'
        run: terraform plan

      - name: ✅ Terraform Apply
        if: github.event.inputs.destroy != 'true'
        run: terraform apply -auto-approve

      - name: ❌ Terraform Destroy
        if: github.event.inputs.destroy == 'true'
        run: terraform destroy -auto-approve

  promote-uat:
    name: 🔁 Promote Dev ➤ UAT
    if: github.ref != 'refs/heads/main' && github.event.inputs.environment == 'uat' && github.event.inputs.destroy != 'true'
    needs: deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: UAT
    environment: uat
    steps:
      - name: Checkout UAT
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS for UAT
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_UAT }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_UAT }}
          aws-region: us-west-2

      - name: Promote Dev to UAT
        run: |
          terraform init
          terraform apply -auto-approve

  deploy-prod:
    name: 🚀 Deploy to Production
    if: github.ref == 'refs/heads/main' && github.event.inputs.environment == 'production'
    needs: deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Prod
    environment: production
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_PROD }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}
          aws-region: us-west-2

      - name: Terraform Init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_PROD }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve
